### PR TITLE
Add support for API Url suffix

### PR DESCRIPTION
**Pull request by lurumad**
Hi @stephaneey 

This PR adds a new field to able to set "API Url suffix" in APIM.

Regards!

### CODE REVIEW

**Comment by rickvanschalkwijk** [comment]
Hi @stephaneey are you expecting to release this change any time soon?

**Comment by stephaneey** [comment]
HI Rick,

It should be release before the end of the week. The API suffix is already implemented. This plus other things I plan to add:

- Inline Swagger or URL-based
- I might include the Client Certificates
- I've already added the versioning scheme (segment, query string or  http header)

So, I'm currently in testing phase and I might release a new version Tomorrow or at latest, next week-end.

Best Regards

**Comment by rickvanschalkwijk** [comment]
@stephaneey, awesome thanks!

**Comment by rickvanschalkwijk** [comment]
@stephaneey, thanks for releasing a new version on such short notice 👍

**Pull request merged**
