### PR TITLE
Fix in versioned API if the version contains a dot

### LINKED ISSUE #49: Create or Update Versioned API 3.3.0: Error when version number contains a dot
Creating or updating a versioned API results in an error when the version contains a dot.

API Name: my-api
API Version: 1.0

_@{code=ValidationError; target=aid; message=Invalid identifier my-api1.0 specified.  Entity Identifier can contain only letters, numbers, and hyphens. The first and last character must be a letter or a number }_

---

Task Version: 3.3.0
Microsoft API Version: 2018-01-01

### PR DESCRIPTION
**Pull request by FelixBoers**
In version 3.3.0 of the task, if we create a new version for a given
API we concat the name of the api with the version. For example:

```powershell
$name="my-api"
$version="1.0"
$url="${name}${version}"
```

Microsoft only allows letters, numbers and hyphens in their identifiers.
Therefore, we've to get rid of the `.` in the id.

As a first solution, we now replace `.` with `-` in the identifier of
the API version.

Fixes #49

### CODE REVIEW

**Comment by FelixBoers** [comment]
A first solution. I haven't tested it yet, though.

**Comment by FelixBoers** [comment]
As part of this pull request, I've changed the indentation of the file. If you want me, to keep this out of the pull request (or create a separate pull request for this), please let me know.

**Comment by stephaneey** [comment]
Hi Felix,

Since I went through multiple changes in parallel and since there is an important bug I just fixed, I'd like to release the new version ASAP so I'll close the pull request and adapt the code myself. Thanks for having spotted the issue and thanks for your contribution.

Best Regards

**Comment by FelixBoers** [comment]
That's fine :). Thanks for your reply!

**Pull request closed without merging**
