### PR TITLE
Add multiple products to API

### LINKED ISSUE #15: Can't add multiple products to API
In API Management i can add multiple products to a API. In the step "API Management - Create or Update API" is can only select one product (or use the product created by previous task) to add to the API. 
Would like to add multiple products to the API.

### PR DESCRIPTION
**Pull request by lurumad**
Resolves #15 

Please review the changes and merge if you think if resolved.

Regards!!!

### CODE REVIEW

**Comment by stephaneey** [comment]
Hello @lurumad ,

Thanks for your contribution, however, I'd prefer not to create a major version our of this change as it is not really major and is perfectly compatible with the existing version. I'd prefer to keep the number of versions low as we duplicate all the SDK files etc. which makes the entire repo very big. So, would you mind simply increasing the minor version number?

Thanks
Best Regards

**Comment by lurumad** [comment]
Hi @stephaneey 

The idea is mantain v2 with my new changes, isn't it?

Regards!

**Comment by stephaneey** [comment]
Yep exactly. I can report your changes myself to v2 if you don't have time.

**Comment by stephaneey** [comment]
Hi @lurumad ,

You were right, I overlooked the fact that you changed the product input type to multiline, this requires indeed a new version to avoid breaking the existing pipelines. So, I'm going to perform regression tests on what you did and merge my own changes (creating groups on the fly) before I publish the extension.

Thanks

**Pull request merged**
